# Generated by Django 4.0.4 on 2022-06-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrec', '0002_icdsearch_rename_user_name_patient_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='medicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(max_length=50)),
            ],
        ),
    ]
