# Generated by Django 4.0.4 on 2022-06-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medrec', '0003_medicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.CharField(max_length=50),
        ),
    ]
